services:
  # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   ports:
  #   - 53:53/udp
  #   - 53:53/tcp
  #   - 67:67/udp
  #   - 8008:80/tcp
  #   # - 443:443/tcp
  #   environment:
  #     TZ: "Australia/Sydney"
  #     ServerIP: {}
  #     ServerIPv6: {}
  #     VIRTUAL_HOST: "pi.hole"
  #     DNSSEC: "true"
  #     # WEBPASSWORD: 'set a secure password here or it will be random'
  #   # pihole and dnsmasq must in different volumes
  #   volumes:
  #   - "pihole:/etc/pihole/"
  #   - "dnsmasq:/etc/dnsmasq.d/"
  #   dns:
  #   - 127.0.0.1
  #   - 1.1.1.1
  #   restart: unless-stopped

  # transmission:
  #   container_name: transmission
  #   image: ghcr.io/linuxserver/transmission:latest
  #   environment:
  #     PUID: 1000
  #     PGID: 1000
  #     TZ: "Australia/Sydney"
  #     TRANSMISSION_WEB_HOME: "/combustion-release/" #optional
  #     USER: user #optional
  #     PASS: pass #optional
  #   volumes:
  #     - "transmission:/config"
  #   ports:
  #     - 9091:9091
  #   restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    command:
      - --http-enabled
    environment:
      TZ: "Australia/Sydney"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - 9000:9000
    restart: always

volumes:
  # pihole:
  # transmission:
  portainer:
